<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>VoiceKit</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../VoiceKit.Core/VoiceKit.Core.csproj" />
    <ProjectReference Include="../VoiceKit.Remote/VoiceKit.Remote.csproj" />
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>
</Project>
